version: '3'
services:
  apache:
    build: ./apache
    ports:
      - 8080:80
    restart: always
    depends_on:
      - mariadb
      - python
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./libros.sql:/docker-entrypoint-initdb.d/setup.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: "0.0.0.0"
      SECRET_KEY: "you-will-never-guess"
      WTF_CSRF_SECRET_KEY: "asdasdas"
    volumes:
      - ./web:/app
    ports:
      - 9094:8080
    depends_on:
      - mariadb
